// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddStreamer(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddStreamer'](arg1, arg2, arg3);
}

export function ConnectToCore(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectToCore'](arg1, arg2, arg3);
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function RemoveStreamer(arg1) {
  return window['go']['main']['App']['RemoveStreamer'](arg1);
}
