// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddStreamer(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddStreamer'](arg1, arg2, arg3);
}

export function ConnectToCore(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectToCore'](arg1, arg2, arg3);
}

export function GetBBAppConfig(arg1) {
  return window['go']['main']['App']['GetBBAppConfig'](arg1);
}

export function GetBBCoreURL() {
  return window['go']['main']['App']['GetBBCoreURL']();
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetOverlayURL(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetOverlayURL'](arg1, arg2, arg3);
}

export function GetSessionStatus() {
  return window['go']['main']['App']['GetSessionStatus']();
}

export function InitializeBBCoreClient(arg1, arg2) {
  return window['go']['main']['App']['InitializeBBCoreClient'](arg1, arg2);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function RefreshToken(arg1) {
  return window['go']['main']['App']['RefreshToken'](arg1);
}

export function RemoveStreamer(arg1) {
  return window['go']['main']['App']['RemoveStreamer'](arg1);
}

export function SaveBBAppConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveBBAppConfig'](arg1, arg2);
}

export function StartPKSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartPKSession'](arg1, arg2, arg3);
}

export function StopPKSession(arg1) {
  return window['go']['main']['App']['StopPKSession'](arg1);
}
