// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddStreamer(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ConnectToCore(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetConnections():Promise<Array<Record<string, string>>>;

export function RemoveStreamer(arg1:string):Promise<void>;
