// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {session} from '../models';
import {api} from '../models';

export function AddStreamer(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ConnectToCore(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetBBCoreURL():Promise<string>;

export function GetConnections():Promise<Array<Record<string, string>>>;

export function GetOverlayURL(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetSessionStatus():Promise<session.Status>;

export function Login(arg1:string,arg2:string):Promise<api.AuthResponse>;

export function RefreshToken(arg1:string):Promise<api.AuthResponse>;

export function RemoveStreamer(arg1:string):Promise<void>;

export function StartPKSession(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StopPKSession(arg1:string):Promise<void>;
