// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {profile} from '../models';
import {listener} from '../models';
import {session} from '../models';

export function AddStreamer(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ConnectToCore(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateProfile(arg1:string,arg2:string,arg3:api.Config):Promise<profile.Profile>;

export function DeleteProfile(arg1:string):Promise<void>;

export function FetchBigoUser(arg1:string):Promise<listener.BigoUserInfo>;

export function FetchConfig(arg1:string):Promise<api.Config>;

export function FetchGlobalIdols():Promise<Array<api.GlobalIdol>>;

export function GetBBAppConfig(arg1:string):Promise<api.Config>;

export function GetBBCoreStreamStatus():Promise<session.BBCoreStreamStatus>;

export function GetBBCoreURL():Promise<string>;

export function GetBigoListenerStatus():Promise<session.BigoListenerStatus>;

export function GetConnections():Promise<Array<Record<string, string>>>;

export function GetGiftLibrary():Promise<Array<api.GiftDefinition>>;

export function GetOverlayURL(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetSessionStatus():Promise<session.Status>;

export function InitializeBBCoreClient(arg1:string,arg2:string):Promise<void>;

export function ListProfiles():Promise<Array<profile.Profile>>;

export function LoadProfile(arg1:string):Promise<profile.Profile>;

export function Login(arg1:string,arg2:string):Promise<api.AuthResponse>;

export function RefreshAuthToken(arg1:string):Promise<api.AuthResponse>;

export function Register(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<api.AuthResponse>;

export function RemoveStreamer(arg1:string):Promise<void>;

export function ResetSession():Promise<void>;

export function SaveBBAppConfig(arg1:string,arg2:api.Config):Promise<void>;

export function SaveGiftLibrary(arg1:Array<api.GiftDefinition>):Promise<void>;

export function SaveGlobalIdols(arg1:Array<api.GlobalIdol>):Promise<void>;

export function StartBBCoreStream(arg1:string,arg2:api.Config,arg3:number):Promise<void>;

export function StartBigoListener(arg1:api.Config):Promise<void>;

export function StartPKSession(arg1:string,arg2:string,arg3:string,arg4:api.Config,arg5:number):Promise<void>;

export function StopBBCoreStream(arg1:string):Promise<void>;

export function StopBigoListener():Promise<void>;

export function StopPKSession(arg1:string):Promise<void>;

export function UpdateProfile(arg1:string,arg2:api.Config):Promise<profile.Profile>;

export function UpdateProfileBigoInfo(arg1:string,arg2:string,arg3:string):Promise<profile.Profile>;

export function ValidateTrial(arg1:Array<api.ValidateTrialStreamer>):Promise<api.ValidateTrialResponse>;
